### ISSUE TITLE
Error while compiling the code

### ISSUE THREAD

**Issue by Asnegha** [ThomasLoke/stock_cutter#4]
I am getting this error while compiling the code. 
_Error:_ **main.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.**

How to resolve it?

**Comment by ThomasLoke** [comment]
Hi @Asnegha, I assume you meant you got this error when trying to execute the program, not when trying to compile it? A quick google search suggests that you may be running the executable on a 32-bit operating system without having compiled a 32-bit binary.

I haven't gotten around to including any specific deployment instructions for this project, so it is currently the responsibility of the user to set up the compilation process correctly to work for whatever system they want to deploy to. On my part, AFAIK, there isn't anything in the code that would prevent it from working on a specific operating system (Windows or otherwise), given the right compilation process.

**Comment by ThomasLoke** [comment]
Having said that, it may be worth trying to remove the `targetver.h` header file and to also remove it's inclusion in `stdafx.h`, and see if that makes a difference? They shouldn't be needed for a console application; it was just extra cruft that was generated by Visual Studio that I didn't think of removing, but might present issues on non-Windows platforms.

**Comment by Asnegha** [comment]
Thank you for the response. It actually made me understand my mistake. But how can we compile multiple .h, .cpp files in folder and link external coin-or header files during compile time in vs code?... or in other words what is the command you used to compile the program?....
_because it is showing me this error when I try to compile :_  
![image](https://github.com/ThomasLoke/stock_cutter/assets/60292462/abc871e9-0125-41da-be0e-d8fba17e40c1)

**Comment by ThomasLoke** [comment]
> But how can we compile multiple .h, .cpp files in folder and link external coin-or header files during compile time in vs code?... or in other words what is the command you used to compile the program?....

I last compiled this code using Visual Studio, which takes care of building the right compiler commands for proper compilation (though, of course, the path to the CBC library was required) without me needing to figure it out. So I'm afraid I can't help you out here. Your compilation errors suggests that the library paths haven't been included correctly, so I would suggest that you try to just compile a single .cpp file that calls a CBC library function. If that can compile, then there shouldn't be any reason why compiling multiple .cpp and .h files would not also work. Either way, I don't believe that it's a problem with the code.
